const API=''; let currentId=null,currentData=null,providerData=null;
const $=id=>document.getElementById(id);
function nav(page){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));$(page).classList.add('active');document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));$('pageTitle').textContent={workspace:'Research Workspace',history:'Research History',sources:'Evidence Sources',graph:'Knowledge Graph',settings:'Provider Settings'}[page];if(page==='history')loadHistory();}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>nav(b.dataset.page));$('newBtn').onclick=()=>{nav('workspace');$('query').focus()};
async function api(path,opt){const r=await fetch(API+path,opt);let d={};try{d=await r.json()}catch{}if(!r.ok)throw new Error(d.detail||'Request failed');return d}
async function boot(){try{await api('/api/health');$('health').textContent='Agent online';document.querySelector('.side-note .dot').classList.add('on');}catch{}providerData=await api('/api/providers');fillModels();}
function fillModels(){for(const [p,id] of [['gemini','geminiModel'],['groq','groqModel']]){const arr=providerData[p]||[];$(id).innerHTML=arr.map(m=>`<option>${m}</option>`).join('');}}
async function connect(p){const key=$(p+'Key').value.trim(),model=$(p+'Model').value;const msg=$(p+'Msg');msg.textContent='Verifying…';msg.className='msg';try{const d=await api('/api/providers/verify',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({provider:p,model,api_key:key})});msg.textContent='✓ '+d.message;msg.className='msg ok';}catch(e){msg.textContent='✕ '+e.message;msg.className='msg err';}}
function addEvent(stage,message){const t=$('timeline');if(t.querySelector('.empty'))t.innerHTML='';const el=document.createElement('div');el.className='event';el.innerHTML=`<span class="event-dot"></span><div><b>${esc(stage)}</b><p>${esc(message)}</p></div>`;t.prepend(el)}
async function start(){const q=$('query').value.trim();if(!q)return alert('Enter a research question first.');let provider='gemini',model=$('geminiModel').value;if(providerData?.saved?.length){const saved=providerData.saved.find(x=>x.connected);if(saved){provider=saved.provider;model=saved.model;}}const urls=$('urls').value.split(',').map(x=>x.trim()).filter(Boolean);const files=[...$('files').files];$('timeline').innerHTML='';$('statusText').textContent='Starting';$('statusDot').classList.add('busy');addEvent('START','Creating an auditable research run');let file_context=[];if(files.length){addEvent('INGEST','Reading local files');const fd=new FormData();files.forEach(f=>fd.append('files',f));try{const uploaded=await api('/api/files',{method:'POST',body:fd});file_context=uploaded.map(x=>x.parsed)}catch(e){addEvent('ERROR',e.message);}}
try{const d=await api('/api/researches',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query:q,provider,model,urls,file_context})});currentId=d.id;poll();}catch(e){addEvent('ERROR',e.message);$('statusText').textContent='Could not start';$('statusDot').classList.remove('busy');}}
$('run').onclick=start;
async function poll(){if(!currentId)return;try{const d=await api('/api/researches/'+currentId);currentData=d;const ev=d.events||[];$('timeline').innerHTML='';ev.forEach(e=>addEvent(e.stage,e.message));$('statusText').textContent=d.status;if(d.status==='completed'){renderResult(d);$('statusDot').classList.remove('busy');return}if(d.status==='failed'){$('statusDot').classList.remove('busy');return}setTimeout(poll,1200);}catch(e){setTimeout(poll,2000)}}
function renderResult(d){$('results').hidden=false;$('resultTitle').textContent=d.title;$('report').innerHTML=md(d.report||'No report returned.');$('rowCount').textContent=(d.dataset||[]).length+' rows';renderTable(d.dataset||[]);$('evidence').innerHTML=(d.evidence||[]).map(e=>`<div class="evidence"><span>${Math.round((e.confidence||0)*100)}%</span><p>${esc(e.claim)}</p><small>${esc(e.quote||'')}</small></div>`).join('')||'<div class="empty">No structured evidence returned.</div>';$('sourceList').innerHTML=(d.sources||[]).map((s,i)=>`<a class="source" href="${escAttr(s.url)}" target="_blank"><span>${i+1}</span><div><b>${esc(s.title||s.url)}</b><small>${esc(s.domain||'')}</small></div></a>`).join('');$('allSources').innerHTML=$('sourceList').innerHTML;renderGraph(d.graph||{});}
function renderTable(rows){const t=$('dataTable');if(!rows.length){t.innerHTML='<tr><td>No structured rows.</td></tr>';return}const keys=[...new Set(rows.flatMap(r=>Object.keys(r)))];t.innerHTML='<thead><tr>'+keys.map(k=>`<th>${esc(k)}</th>`).join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+keys.map(k=>`<td>${esc(r[k]??'')}</td>`).join('')+'</tr>').join('')+'</tbody>'}
function renderGraph(g){const ents=g.entities||[];const rel=g.relationships||[];$('graphView').innerHTML=ents.length?`<div class="nodes">${ents.map((e,i)=>`<div class="node" style="--i:${i}"><b>${esc(e.name)}</b><small>${esc(e.type||'entity')}</small></div>`).join('')}</div><div class="relations">${rel.map(r=>`<span>${esc(r.source)} <b>→ ${esc(r.type||'related')}</b> ${esc(r.target)}</span>`).join('')}</div>`:'No entities returned.'}
async function loadHistory(){const rows=await api('/api/researches');$('historyList').innerHTML=rows.map(r=>`<button class="history-row" onclick="openResearch(${r.id})"><div><b>${esc(r.title)}</b><small>${new Date(r.created_at*1000).toLocaleString()}</small></div><span class="badge ${r.status}">${r.status}</span></button>`).join('')||'<div class="empty">No research runs yet.</div>'}
async function openResearch(id){currentId=id;currentData=await api('/api/researches/'+id);nav('workspace');renderResult(currentData)}
$('refreshHistory').onclick=loadHistory;
document.querySelectorAll('[data-export]').forEach(b=>b.onclick=()=>{if(currentId)location.href=`/api/researches/${currentId}/export.${b.dataset.export}`});
function esc(x){return String(x).replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function escAttr(x){return esc(x).replace(/"/g,'&quot;')}
function md(s){return esc(s).replace(/^### (.*)$/gm,'<h4>$1</h4>').replace(/^## (.*)$/gm,'<h3>$1</h3>').replace(/^# (.*)$/gm,'<h2>$1</h2>').replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\n\n/g,'</p><p>').replace(/\n/g,'<br>');}
boot();
